# Generated by Django 3.0.6 on 2020-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanceapp', '0003_auto_20200815_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
