# Generated by Django 3.0.6 on 2020-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanceapp', '0005_userdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(default='pic.png', null=True, upload_to='profile_pics'),
        ),
    ]
